import {
  type LucideIcon,
  KeyRound,
  Gauge,
  Lightbulb,
  Search,
  Trophy,
  Network,
  ListFilter,
  Building2,
  BarChart,
  Signal,
  AreaChart,
  Mountain,
  DollarSign,
  Link,
  Link2,
  List,
  Unlink2,
  Calculator,
  Repeat,
  PieChart,
  Unlink,
  Gem,
  Swords,
  Anchor,
  ShieldCheck,
  Book,
  ArrowRightCircle,
  GaugeCircle,
  Scaling,
  Eye,
  Users,
  FileCode2,
  Replace,
  Monitor,
  Code2,
  CircleDollarSign,
  Share2,
  PenSquare,
  QrCode,
  Route,
  FileTerminal,
  Twitter,
  Wifi,
  Palette,
  ShieldAlert,
  Camera,
  Mail,
  Smartphone,
  FileMinus2,
  FileCog,
  Scissors,
  ExternalLink,
  FileCode,
  Locate,
  Server,
  Ratio,
  Shuffle,
  Diff,
  Bot,
  History,
  Info,
  BarChart3,
  BarChart4,
  ArrowRight,
  Copy,
  EyeOff,
  User,
  FileArchive,
  Lock,
  FileText,
  Map,
  AppWindow,
  Globe,
  WifiOff,
  CalendarDays,
  Crown,
  Database,
  ArrowRightLeft,
  ShieldOff,
  Clock,
  Star,
  FileSearch2,
  ShieldX,
  Tags,
  PenTool,
} from 'lucide-react';

export type Tool = {
  name: string;
  description: string;
  slug: string;
  category: string;
  icon: LucideIcon;
};

export type ToolCategory = {
  name: string;
  description: string;
  tools: Tool[];
};

const keywordsTools: Tool[] = [
    { name: 'Keyword Position', slug: 'keyword-position', description: 'Check your website\'s keyword ranking in SERPs.', category: 'Keywords Tools', icon: Map },
    { name: 'Keywords Density Checker', slug: 'keywords-density-checker', description: 'Analyze the keyword density of your web page.', category: 'Keywords Tools', icon: Gauge },
    { name: 'Keywords Suggestions Tool', slug: 'keywords-suggestions-tool', description: 'Get new keyword ideas for your content.', category: 'Keywords Tools', icon: Lightbulb },
    { name: 'Keyword Research Tool', slug: 'keyword-research-tool', description: 'Discover valuable keywords for your SEO strategy.', category: 'Keywords Tools', icon: Search },
    { name: 'Keyword Competition Tool', slug: 'keyword-competition-tool', description: 'Analyze the competition for your target keywords.', category: 'Keywords Tools', icon: Trophy },
    { name: 'Related Keywords Finder', slug: 'related-keywords-finder', description: 'Find keywords related to your main search term.', category: 'Keywords Tools', icon: Network },
    { name: 'Long Tail Keyword Suggestion', slug: 'long-tail-keyword-suggestion-tool', description: 'Generate long-tail keywords to attract specific traffic.', category: 'Keywords Tools', icon: ListFilter },
    { name: 'Keywords Rich Domains Suggestions', slug: 'keywords-rich-domains-suggestions-tool', description: 'Find domain names rich with your keywords.', category: 'Keywords Tools', icon: Building2 },
    { name: 'SEO Keyword Competition Analysis', slug: 'seo-keyword-competition-analysis', description: 'In-depth analysis of keyword competition.', category: 'Keywords Tools', icon: BarChart },
    { name: 'Live Keyword Analyzer', slug: 'live-keyword-analyzer', description: 'Analyze keyword usage on any webpage in real-time.', category: 'Keywords Tools', icon: Signal },
    { name: 'Keyword Overview Tool', slug: 'keyword-overview-tool', description: 'Get a comprehensive overview of any keyword.', category: 'Keywords Tools', icon: AreaChart },
    { name: 'Keyword Difficulty Checker', slug: 'keyword-difficulty-checker', description: 'Assess how difficult it is to rank for a keyword.', category: 'Keywords Tools', icon: Mountain },
    { name: 'Paid Keyword Finder', slug: 'paid-keyword-finder', description: 'Discover keywords your competitors are paying for.', category: 'Keywords Tools', icon: DollarSign },
];

const backlinkTools: Tool[] = [
    { name: 'Backlink Checker', slug: 'backlink-checker', description: 'See who is linking to your website.', category: 'BackLink Tools', icon: Link },
    { name: 'Backlink Maker', slug: 'backlink-maker', description: 'Generate high-quality backlinks for your website.', category: 'BackLink Tools', icon: Link2 },
    { name: 'Website Link Count Checker', slug: 'website-link-count-checker', description: 'Count the total number of links on a page.', category: 'BackLink Tools', icon: List },
    { name: 'Website Broken Link Checker', slug: 'website-broken-link-checker', description: 'Find and fix broken links on your site.', category: 'BackLink Tools', icon: Unlink2 },
    { name: 'Link Price Calculator', slug: 'link-price-calculator', description: 'Estimate the price of a backlink from any website.', category: 'BackLink Tools', icon: Calculator },
    { name: 'Reciprocal Link Checker', slug: 'reciprocal-link-checker', description: 'Check if your linking partners are still linking to you.', category: 'BackLink Tools', icon: Repeat },
    { name: 'Website Link Analyzer Tool', slug: 'website-link-analyzer-tool', description: 'Analyze the links on your website.', category: 'BackLink Tools', icon: PieChart },
    { name: 'Broken Backlink Checker', slug: 'broken-backlink-checker', description: 'Find broken backlinks pointing to your site.', category: 'BackLink Tools', icon: Unlink },
    { name: 'Valuable Backlink Checker', slug: 'valuable-backlink-checker', description: 'Identify the most valuable backlinks to your site.', category: 'BackLink Tools', icon: Gem },
    { name: 'Backlinks Competitors', slug: 'backlinks-competitors', description: 'Analyze the backlink profiles of your competitors.', category: 'BackLink Tools', icon: Swords },
    { name: 'Anchor Text Distribution', slug: 'anchor-text-distribution', description: 'Check the distribution of anchor texts for your links.', category: 'BackLink Tools', icon: Anchor },
];

const websiteManagementTools: Tool[] = [
    { name: 'Website SEO Score Checker', slug: 'website-seo-score-checker', description: 'Get a comprehensive SEO score for your website.', category: 'Website Management Tools', icon: ShieldCheck },
    { name: 'Google Pagerank Checker', slug: 'google-pagerank-checker', description: 'Check the PageRank of any web page.', category: 'Website Management Tools', icon: Book },
    { name: 'Online Ping Website Tool', slug: 'online-ping-website-tool', description: 'Ping search engines to crawl your website.', category: 'Website Management Tools', icon: ArrowRightCircle },
    { name: 'Page Speed Test', slug: 'page-speed-test', description: 'Analyze your website\'s loading speed.', category: 'Website Management Tools', icon: GaugeCircle },
    { name: 'Website Page Size Checker', slug: 'website-page-size-checker', description: 'Check the size of your web pages.', category: 'Website Management Tools', icon: Scaling },
    { name: 'Website Page Snooper', slug: 'website-page-snooper', description: 'View the source code and headers of any website.', category: 'Website Management Tools', icon: Eye },
    { name: 'Get HTTP Headers', slug: 'get-http-headers', description: 'Check the HTTP headers of any URL.', category: 'Website Management Tools', icon: FileTerminal },
    { name: 'XML Sitemap Generator', slug: 'xml-sitemap-generator', description: 'Create an XML sitemap for your website.', category: 'Website Management Tools', icon: FileCode2 },
    { name: 'URL Rewriting Tool', slug: 'url-rewriting-tool', description: 'Generate SEO-friendly URLs.', category: 'Website Management Tools', icon: Replace },
    { name: 'What is My Screen Resolution', slug: 'what-is-my-screen-resolution', description: 'Find out your current screen resolution.', category: 'Website Management Tools', icon: Monitor },
    { name: 'URL Encoder Decoder', slug: 'url-encoder-decoder', description: 'Encode or decode URLs.', category: 'Website Management Tools', icon: Code2 },
    { name: 'Adsense Calculator', slug: 'adsense-calculator', description: 'Estimate your potential earnings from Google AdSense.', category: 'Website Management Tools', icon: CircleDollarSign },
    { name: 'Open Graph Checker', slug: 'open-graph-checker', description: 'Check the Open Graph tags of a webpage.', category: 'Website Management Tools', icon: Share2 },
    { name: 'Open Graph Generator', slug: 'open-graph-generator', description: 'Generate Open Graph tags for your website.', category: 'Website Management Tools', icon: PenSquare },
    { name: 'QR Code Generator', slug: 'qr-code-generator', description: 'Create QR codes for your URLs.', category: 'Website Management Tools', icon: QrCode },
    { name: 'Htaccess Redirect Generator', slug: 'htaccess-redirect-generator', description: 'Generate htaccess redirect code.', category: 'Website Management Tools', icon: Route },
];

const websiteTrackingTools: Tool[] = [
    { name: 'Reverse IP Lookup', slug: 'reverse-ip-lookup', description: 'Find domains hosted on the same IP address.', category: 'Website Tracking Tools', icon: Locate },
    { name: 'Check Server Status', slug: 'check-server-status', description: 'Check the status of your web server.', category: 'Website Tracking Tools', icon: Server },
    { name: 'Class C IP Checker', slug: 'class-c-ip-checker', description: 'Check the Class C IP of a domain.', category: 'Website Tracking Tools', icon: Network },
    { name: 'Code To Text Ratio Checker', slug: 'code-to-text-ratio-checker', description: 'Analyze the code to text ratio of your pages.', category: 'Website Tracking Tools', icon: Ratio },
    { name: 'Alexa Rank Comparison', slug: 'alexa-rank-comparison', description: 'Compare the Alexa rank of multiple websites.', category: 'Website Tracking Tools', icon: Shuffle },
    { name: 'Page Comparison', slug: 'page-comparison', description: 'Compare two web pages side by side.', category: 'Website Tracking Tools', icon: Diff },
    { name: 'Spider Simulator', slug: 'spider-simulator', description: 'See how search engine spiders view your website.', category: 'Website Tracking Tools', icon: Bot },
    { name: 'Comparison Search', slug: 'comparison-search', description: 'Search and compare results from multiple search engines.', category: 'Website Tracking Tools', icon: Search },
    { name: 'Google Cache Checker', slug: 'google-cache-checker', description: 'Check the cached version of your pages in Google.', category: 'Website Tracking Tools', icon: History },
    { name: 'Whois Lookup', slug: 'whois-lookup', description: 'Get WHOIS information for any domain.', category: 'Website Tracking Tools', icon: Info },
    { name: 'Mozrank Checker', slug: 'mozrank-checker', description: 'Check the MozRank of any URL.', category: 'Website Tracking Tools', icon: BarChart3 },
    { name: 'Page Authority Checker', slug: 'page-authority-checker', description: 'Check the Page Authority of a web page.', category: 'Website Tracking Tools', icon: BarChart4 },
    { name: 'Google Index Checker', slug: 'google-index-checker', description: 'Check if your pages are indexed by Google.', category: 'Website Tracking Tools', icon: Search },
    { name: 'Alexa Rank Checker', slug: 'alexa-rank-checker', description: 'Check the Alexa rank of any website.', category: 'Website Tracking Tools', icon: BarChart },
    { name: 'Redirect Checker', slug: 'redirect-checker', description: 'Check the redirects of any URL.', category: 'Website Tracking Tools', icon: ArrowRight },
    { name: 'Similar Site Checker', slug: 'similar-site-checker', description: 'Find websites similar to yours.', category: 'Website Tracking Tools', icon: Copy },
    { name: 'Cloaking Checker', slug: 'cloaking-checker', description: 'Check if a website is cloaking.', category: 'Website Tracking Tools', icon: EyeOff },
    { name: 'Google Malware Checker', slug: 'google-malware-checker', description: 'Scan a website for malware with Google.', category: 'Website Tracking Tools', icon: ShieldAlert },
    { name: 'Find Facebook ID', slug: 'find-facebook-id', description: 'Find the numeric ID of a Facebook profile.', category: 'Website Tracking Tools', icon: User },
    { name: 'Check GZIP compression', slug: 'check-gzip-compression', description: 'Check if GZIP compression is enabled on your site.', category: 'Website Tracking Tools', icon: FileArchive },
    { name: 'SSL Checker', slug: 'ssl-checker', description: 'Verify the SSL certificate of your website.', category: 'Website Tracking Tools', icon: Lock },
    { name: 'Find Blog Sites', slug: 'find-blog-sites', description: 'Discover blogs in your niche.', category: 'Website Tracking Tools', icon: FileText },
    { name: 'GEO IP Locator', slug: 'geo-ip-locator', description: 'Find the geographical location of an IP address.', category: 'Website Tracking Tools', icon: Map },
    { name: 'Apps Rank Tracking Tool', slug: 'apps-rank-tracking-tool', description: 'Track the ranking of your mobile apps.', category: 'Website Tracking Tools', icon: AppWindow },
    { name: 'What Is My Browser', slug: 'what-is-my-browser', description: 'Get details about your current web browser.', category: 'Website Tracking Tools', icon: Globe },
    { name: 'Check Social Status', slug: 'check-social-status', description: 'Check your social media presence and status.', category: 'Website Tracking Tools', icon: Users },
    { name: 'Is It Down', slug: 'is-it-down', description: 'Check if a website is down for everyone or just you.', category: 'Website Tracking Tools', icon: WifiOff },
];

const domainsTools: Tool[] = [
    { name: 'Domain Age Checker', slug: 'domain-age-checker', description: 'Find out the age of any domain.', category: 'Domains Tools', icon: CalendarDays },
    { name: 'Domain Authority Checker', slug: 'domain-authority-checker', description: 'Check the Domain Authority of a website.', category: 'Domains Tools', icon: Crown },
    { name: 'Domain IP Lookup', slug: 'domain-ip-lookup', description: 'Find the IP address of any domain.', category: 'Domains Tools', icon: Network },
    { name: 'Domain Hosting Checker', slug: 'domain-hosting-checker', description: 'Find out who is hosting a website.', category: 'Domains Tools', icon: Server },
    { name: 'Find DNS records', slug: 'find-dns-records', description: 'Check the DNS records of a domain.', category: 'Domains Tools', icon: Database },
    { name: 'Domain Name Search', slug: 'domain-name-search', description: 'Search for available domain names.', category: 'Domains Tools', icon: Search },
    { name: 'Domain To IP', slug: 'domain-to-ip', description: 'Convert a domain name to an IP address.', category: 'Domains Tools', icon: ArrowRightLeft },
    { name: 'Check Blacklist IP', slug: 'check-blacklist-ip', description: 'Check if an IP is on a blacklist.', category: 'Domains Tools', icon: ShieldOff },
    { name: 'Find Expired Domains', slug: 'find-expired-domains', description: 'Find recently expired domain names.', category: 'Domains Tools', icon: Clock },
    { name: 'Bulk Domain Rating Checker', slug: 'bulk-domain-rating-checker', description: 'Check the rating of multiple domains at once.', category: 'Domains Tools', icon: Star },
    { name: 'Index Pages Checker', slug: 'index-pages-checker', description: 'Check the number of indexed pages for a domain.', category: 'Domains Tools', icon: FileSearch2 },
    { name: 'Spam Score Checker', slug: 'spam-score-checker', description: 'Check the spam score of a website.', category: 'Domains Tools', icon: ShieldX },
];

const metaTagsTools: Tool[] = [
    { name: 'Meta Tags Analyzer', slug: 'meta-tags-analyzer', description: 'Analyze the meta tags of your web pages.', category: 'Meta Tags Tools', icon: Tags },
    { name: 'Meta Tag Generator', slug: 'meta-tag-generator', description: 'Generate meta tags for your website using AI.', category: 'Meta Tags Tools', icon: PenTool },
];

export const toolCategories: ToolCategory[] = [
    { name: 'Keywords Tools', description: 'Powerful and efficient keyword tools for thorough research and analysis.', tools: keywordsTools },
    { name: 'Backlink Tools', description: 'A set of backlink analysis tools to give you a comprehensive inside view of your link profile.', tools: backlinkTools },
    { name: 'Website Management Tools', description: 'Enhance website performance with these management tools and in-depth web analysis.', tools: websiteManagementTools },
    { name: 'Website Tracking Tools', description: 'Measure, monitor, and keep track of your website’s performance.', tools: websiteTrackingTools },
    { name: 'Domains Tools', description: 'Find out domain age, authority, DNS records, or expired domains.', tools: domainsTools },
    { name: 'Meta Tags Tools', description: 'Create new meta tags or analyze existing ones for an in-depth analysis.', tools: metaTagsTools },
];
