// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
// To update this file, edit the 'firebase' section in your backend.json file.
// For more information, see the Firebase Studio documentation.

import type { FirebaseOptions } from 'firebase/app';

/**
 * The Firebase configuration object.
 *
 * This object is used to initialize the Firebase app.
 * It is safe to expose this configuration to the client.
 *
 * For more information, see the Firebase documentation:
 * https://firebase.google.com/docs/web/setup#config-object
 */
export const firebaseConfig: FirebaseOptions = {
  apiKey: process.env.NEXT_PUBLIC_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_APP_ID,
};
