'use server';

import { config } from 'dotenv';
config();

import '@/ai/flows/generate-meta-tags.ts';
import '@/ai/flows/check-keyword-position.ts';
import '@/ai/flows/check-keyword-density.ts';
import '@/ai/flows/get-keyword-suggestions.ts';
import '@/ai/flows/keyword-research.ts';
import '@/ai/flows/check-keyword-competition.ts';
import '@/ai/flows/find-related-keywords.ts';
import '@/ai/flows/get-long-tail-keyword-suggestions.ts';
import '@/ai/flows/get-keyword-rich-domains.ts';
import '@/ai/flows/backlink-checker.ts';
import '@/ai/flows/backlink-maker.ts';
import '@/aiflows/seo-keyword-competition-analysis.ts';
import '@/ai/flows/live-keyword-analyzer.ts';
import '@/ai/flows/keyword-overview.ts';
import '@/ai/flows/keyword-difficulty-checker.ts';
import '@/ai/flows/paid-keyword-finder.ts';
import '@/ai/flows/website-link-count-checker.ts';
import '@/ai/flows/website-broken-link-checker.ts';
import '@/ai/flows/link-price-calculator.ts';
import '@/ai/flows/reciprocal-link-checker.ts';
import '@/ai/flows/website-seo-score-checker.ts';
import '@/ai/flows/google-pagerank-checker.ts';
import '@/ai/flows/online-ping-website-tool.ts';
import '@/ai/flows/website-link-analyzer-tool.ts';
import '@/ai/flows/broken-backlink-checker.ts';
import '@/ai/flows/valuable-backlink-checker.ts';
import '@/ai/flows/backlinks-competitors.ts';
import '@/ai/flows/anchor-text-distribution.ts';
import '@/ai/flows/page-speed-test.ts';
import '@/ai/flows/website-page-size-checker.ts';
import '@/ai/flows/website-page-snooper.ts';
import '@/ai/flows/xml-sitemap-generator.ts';
import '@/ai/flows/url-rewriting-tool.ts';
import '@/ai/flows/adsense-calculator.ts';
import '@/ai/flows/open-graph-generator.ts';
